// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oefentoets1MVC.Data;

#nullable disable

namespace Oefentoets1MVC.Migrations
{
    [DbContext(typeof(CijferRegistratieDBContext))]
    [Migration("20230331065110_StudentType")]
    partial class StudentType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("Oefentoets1MVC.Data.Entities.Poging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jaar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resultaat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("VakNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VakNaam");

                    b.ToTable("Pogingen");
                });

            modelBuilder.Entity("Oefentoets1MVC.Data.Entities.Vak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vakken");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EC = 4,
                            Naam = "Server"
                        },
                        new
                        {
                            Id = 2,
                            EC = 4,
                            Naam = "C#"
                        },
                        new
                        {
                            Id = 3,
                            EC = 3,
                            Naam = "Databases"
                        },
                        new
                        {
                            Id = 4,
                            EC = 3,
                            Naam = "UML"
                        },
                        new
                        {
                            Id = 5,
                            EC = 9,
                            Naam = "KBS"
                        });
                });

            modelBuilder.Entity("Oefentoets1MVC.Data.Entities.Poging", b =>
                {
                    b.HasOne("Oefentoets1MVC.Data.Entities.Vak", "Vak")
                        .WithMany("Pogingen")
                        .HasForeignKey("VakNaam")
                        .HasPrincipalKey("Naam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vak");
                });

            modelBuilder.Entity("Oefentoets1MVC.Data.Entities.Vak", b =>
                {
                    b.Navigation("Pogingen");
                });
#pragma warning restore 612, 618
        }
    }
}
